enum NotificationType {
  CONFIRMED_ORDER = 'CONFIRMED_ORDER',
  DELIVERED = 'DELIVERED',
  EXPIRED = 'EXPIRED',
  GENERAL = 'GENERAL',
  IN_DELIVERY = 'IN_DELIVERY',
  NEW_ORDER = 'NEW_ORDER',
  ORDER_CANCELED_BY_STORE = 'ORDER_CANCELED_BY_STORE',
  ORDER_CANCELED_BY_USER = 'ORDER_CANCELED_BY_USER',
  RATING = 'RATING',
  RATING_REQUEST = 'RATING_REQUEST',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
}

export default NotificationType;
