enum Status {
  OPEN = 'OPEN',
  CONFIRMED = 'CONFIRMED',
  ON_DELIVERY = 'ON_DELIVERY',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  CANCELED_BY_USER = 'CANCELED_BY_USER',
  CANCELED_BY_STORE = 'CANCELED_BY_STORE',
  EXPIRED = 'EXPIRED',
  DELIVERED = 'DELIVERED',
}

export default Status;
